/**
 * Ali Capa print catalogue, the single source of truth.
 *
 * To add a future print:
 * 1. Add optimized files at /images/prints/<slug>.jpg and <slug>-mockup.jpg.
 * 2. Copy one work object below and update its metadata and variants.
 * 3. Run `npm test` and `npm run validate` before deployment.
 *
 * Product prices, identifiers, availability and presentation are read from this
 * file by both the public Prints page and the private checkout functions.
 */

export const PRINT_CATEGORIES = Object.freeze({
  open: Object.freeze({
    id: "open",
    eyebrow: "Open editions",
    title: "Dream Editions",
    revealLabel: "Dream Edition",
    overviewDescription: "Open photographic editions, printed on lustre paper.",
    deepDescription: "Open photographic editions, printed on lustre paper.",
  }),
  collector: Object.freeze({
    id: "collector",
    eyebrow: "Limited editions",
    title: "Collector Editions",
    revealLabel: "Collector Edition",
    overviewDescription: "Limited photographic editions, printed on Hahnemühle Pearl and accompanied by a signed Certificate of Authenticity.",
    deepDescription: "Limited photographic editions, printed on Hahnemühle Pearl and accompanied by a signed Certificate of Authenticity.",
  }),
});

export const PRINT_CATALOG = Object.freeze([
  Object.freeze({
    id: "nine",
    title: "NiNE",
    category: "book",
    order: 0,
    previewPath: "/images/hero-1.jpg",
    description: "A 132-page fine art photobook documenting nine years across ten countries.",
    variants: Object.freeze([
      Object.freeze({
        id: "nine-europe-softcover",
        label: "European Softcover",
        storeSku: "NINE-A4-SOFT-EU",
        provider: "Prodigi",
        providerSku: "BOOK-FE-A4-P-SOFT-G",
        paper: "150 gsm gloss interior · matte cover",
        size: "A4 · 210 × 297 mm",
        priceCents: 5500,
        availability: "available",
        productType: "book",
        fulfillment: Object.freeze({
          mode: "prodigi-live",
          attributes: Object.freeze({ pages: 134 }),
        }),
      }),
    ]),
  }),
  Object.freeze({
    id: "ataquas",
    title: "AtaquaS",
    category: "open",
    order: 1,
    artworkPath: "/images/prints/ataquas.jpg",
    previewPath: "/images/prints/ataquas-preview.jpg",
    mockupPath: "/images/prints/ataquas-mockup.jpg",
    aspectRatio: "2:3 portrait",
    borderMm: 0,
    cardSummary: "Dream Edition · €30",
    description: "A crown of small white flowers, a gaze painted blue, and a hand still bright with yellow. AtaquaS holds one saturated, suspended moment. It is playful, intimate, and entirely alive.",
    variants: Object.freeze([
      Object.freeze({
        id: "ataquas-open",
        label: "Dream Edition",
        storeSku: "ATQ-LPP-30X45",
        provider: "Prodigi",
        providerSku: "GLOBAL-PAP-12X18",
        paper: "Lustre Photo Paper (LPP), 240 gsm",
        size: "30 × 45 cm / 12 × 18 in",
        priceCents: 3000,
        availability: "available",
        fulfillment: Object.freeze({ mode: "prodigi-live" }),
      }),
    ]),
  }),
  Object.freeze({
    id: "eclaircisse",
    title: "EclaircissE",
    category: "open",
    order: 2,
    artworkPath: "/images/prints/eclaircisse.jpg",
    artworkWebpPath: "/images/prints/eclaircisse.webp",
    previewPath: "/images/prints/eclaircisse-preview.jpg",
    mockupPath: "/images/prints/eclaircisse-mockup.jpg",
    aspectRatio: "4:5 portrait",
    borderMm: 0,
    cardSummary: "Dream Edition · €35",
    description: "Light breaks across a body in motion, dissolving the boundary between waking and dreaming. EclaircissE is warmth, blur, and surrender held inside a single frame.",
    variants: Object.freeze([
      Object.freeze({
        id: "eclaircisse-open",
        label: "Dream Edition",
        storeSku: "ECL-LPP-40X50",
        provider: "Prodigi",
        providerSku: "GLOBAL-PAP-16X20",
        paper: "Lustre Photo Paper (LPP), 240 gsm",
        size: "40 × 50 cm / 16 × 20 in",
        priceCents: 3500,
        availability: "available",
        fulfillment: Object.freeze({ mode: "prodigi-live" }),
      }),
    ]),
  }),
  Object.freeze({
    id: "oppia",
    title: "Öppiä",
    category: "open",
    order: 3,
    artworkPath: "/images/prints/oppia.jpg",
    artworkWebpPath: "/images/prints/oppia.webp",
    previewPath: "/images/prints/oppia-preview.jpg",
    mockupPath: "/images/prints/oppia-mockup.jpg",
    aspectRatio: "4:3 landscape collage",
    borderMm: 0,
    cardSummary: "Dream Edition · Available soon",
    description: "A constellation of painted gestures, colour, and repeated presence. Öppiä is still being rebuilt from the archive; the image shown here is a preview, not the final work.",
    variants: Object.freeze([
      Object.freeze({
        id: "oppia-open",
        label: "Dream Edition",
        storeSku: "OPP-PENDING",
        provider: "Prodigi",
        providerSku: "",
        paper: "Lustre Photo Paper (LPP), 240 gsm",
        size: "Final landscape dimensions in development",
        priceCents: null,
        availability: "upcoming",
        fulfillment: Object.freeze({ mode: "unavailable" }),
      }),
    ]),
  }),
  Object.freeze({
    id: "independienta",
    title: "IndepenDienta",
    category: "open",
    order: 4,
    artworkPath: "/images/prints/independienta.jpg",
    artworkWebpPath: "/images/prints/independienta.webp",
    previewPath: "/images/prints/independienta-preview.jpg",
    mockupPath: "/images/prints/independienta-mockup.jpg",
    aspectRatio: "4:3 landscape collage",
    borderMm: 0,
    cardSummary: "Dream Edition · Available soon",
    description: "Eight private moments are held inside one frame. Warm light and inward gestures follow a woman becoming her own shelter. IndepenDienta is still being rebuilt; this remains a preview of the final work.",
    variants: Object.freeze([
      Object.freeze({
        id: "independienta-open",
        label: "Dream Edition",
        storeSku: "IND-PENDING",
        provider: "Prodigi",
        providerSku: "",
        paper: "Lustre Photo Paper (LPP), 240 gsm",
        size: "Final landscape dimensions in development",
        priceCents: null,
        availability: "upcoming",
        fulfillment: Object.freeze({ mode: "unavailable" }),
      }),
    ]),
  }),
  Object.freeze({
    id: "kaisar",
    title: "K.aisa.R",
    category: "collector",
    order: 1,
    artworkPath: "/images/prints/kaisar.jpg",
    artworkWebpPath: "/images/prints/kaisar.webp",
    previewPath: "/images/prints/kaisar-preview.jpg",
    mockupPath: "/images/prints/kaisar-mockup.jpg",
    aspectRatio: "2:3 portrait",
    borderMm: 0,
    cardSummary: "Presence and Immersion · from €250",
    description: "Warm shadow, red silk, and a small offering of white flowers. K.aisa.R turns a backward glance into something between invitation and farewell. It is quiet, self-possessed, and impossible to hurry.",
    certificate: "Clean",
    letterIncluded: true,
    variants: Object.freeze([
      Object.freeze({
        id: "kaisar-presence",
        label: "Presence",
        storeSku: "KSR-PRL-PRESENCE-60X90",
        provider: "Creativehub / theprintspace",
        providerSku: "V-XL076PZL",
        paper: "Hahnemühle Pearl, 285 gsm Giclée",
        size: "60 × 90 cm / 24 × 35 in",
        priceCents: 25000,
        availability: "available",
        editionSize: 5,
        soldCount: 0,
        fulfillment: Object.freeze({
          mode: "configured-fixed",
          envPrefix: "KAISAR_PRESENCE",
          shippingCents: Object.freeze({ GB: 900, DE: 900, EU: 1900, EFTA: 2100, US: 3100, CA: 4400, ANZ: 8200, ROW: 8200 }),
          providerPrintCostCents: 6490,
          providerExtrasCents: 488,
          providerShippingEstimateCents: Object.freeze({ GB: 695, DE: 695, EU: 1463, EFTA: 1960, US: 2867, CA: 4095, ANZ: 7697, ROW: 7697 }),
        }),
      }),
      Object.freeze({
        id: "kaisar-immersion",
        label: "Immersion",
        storeSku: "KSR-PRL-IMMERSION-80X120",
        provider: "Creativehub / theprintspace",
        providerSku: "V-Y6L6H5YT",
        paper: "Hahnemühle Pearl, 285 gsm Giclée",
        size: "80 × 120 cm / 31 × 47 in",
        priceCents: 35000,
        availability: "available",
        editionSize: 5,
        soldCount: 0,
        fulfillment: Object.freeze({
          mode: "configured-fixed",
          envPrefix: "KAISAR_IMMERSION",
          shippingCents: Object.freeze({ GB: 900, DE: 900, EU: 1900, EFTA: 2100, US: 3100, CA: 4400, ANZ: 8200, ROW: 8200 }),
          providerPrintCostCents: 11268,
          providerExtrasCents: 488,
          providerShippingEstimateCents: Object.freeze({ GB: 695, DE: 695, EU: 1463, EFTA: 1960, US: 2867, CA: 4095, ANZ: 7697, ROW: 7697 }),
        }),
      }),
    ]),
  }),
  Object.freeze({
    id: "merano",
    title: "Mèranö",
    category: "collector",
    order: 2,
    artworkPath: "/images/prints/merano.jpg",
    previewPath: "/images/prints/merano-preview.jpg",
    mockupPath: "/images/prints/merano-mockup.jpg",
    aspectRatio: "4:5 portrait",
    borderMm: 25,
    cardSummary: "Edition of 10 · €150",
    description: "A pale flower remains sharply present while the body begins to soften into memory. Mèranö lives in that gentle distance between touch and disappearance, where tenderness refuses to be hurried.",
    certificate: "Clean",
    letterIncluded: true,
    variants: Object.freeze([
      Object.freeze({
        id: "merano-reverie",
        label: "Reverie",
        storeSku: "MER-PRL-REVERIE-60X75",
        provider: "Creativehub / theprintspace",
        providerSku: "V-GDH2VKCH",
        paper: "Hahnemühle Pearl, 285 gsm Giclée",
        size: "50 × 40 cm / 20 × 16 in",
        priceCents: 15000,
        availability: "available",
        editionSize: 10,
        soldCount: 0,
        fulfillment: Object.freeze({
          mode: "configured-fixed",
          envPrefix: "MERANO_REVERIE",
          shippingCents: Object.freeze({ GB: 900, DE: 900, EU: 1900, EFTA: 2100, US: 3100, CA: 4400, ANZ: 8200, ROW: 8200 }),
          providerPrintCostCents: 5753,
          providerExtrasCents: 488,
          providerShippingEstimateCents: Object.freeze({ GB: 695, DE: 695, EU: 1463, EFTA: 1960, US: 2867, CA: 4095, ANZ: 7697, ROW: 7697 }),
        }),
      }),
    ]),
  }),
  Object.freeze({
    id: "raabta",
    title: "Ràábta",
    category: "collector",
    order: 3,
    artworkPath: "/images/prints/raabta.jpg",
    artworkWebpPath: "/images/prints/raabta.webp",
    previewPath: "/images/prints/raabta-preview.jpg",
    mockupPath: "/images/prints/raabta-mockup.jpg",
    aspectRatio: "4:5 portrait",
    borderMm: 25,
    cardSummary: "Edition of 10 · €200",
    description: "Hair, pearls, and skin move between concealment and revelation. Ràábta is not about what is hidden. It is about the trust held inside vulnerability, and the quiet moment when presence becomes connection.",
    certificate: "Clean",
    letterIncluded: true,
    variants: Object.freeze([
      Object.freeze({
        id: "raabta-veil",
        label: "Veil",
        storeSku: "RBT-PRL-VEIL-40X50",
        provider: "Creativehub / theprintspace",
        providerSku: "V-K5SCKYN3",
        paper: "Hahnemühle Pearl, 285 gsm Giclée",
        size: "75 × 60 cm / 30 × 24 in",
        priceCents: 20000,
        availability: "available",
        editionSize: 10,
        soldCount: 0,
        fulfillment: Object.freeze({
          mode: "configured-fixed",
          envPrefix: "RAABTA_VEIL",
          shippingCents: Object.freeze({ GB: 900, DE: 900, EU: 1900, EFTA: 2100, US: 3100, CA: 4400, ANZ: 8200, ROW: 8200 }),
          providerPrintCostCents: 2813,
          providerExtrasCents: 488,
          providerShippingEstimateCents: Object.freeze({ GB: 695, DE: 695, EU: 1463, EFTA: 1960, US: 2867, CA: 4095, ANZ: 7697, ROW: 7697 }),
        }),
      }),
    ]),
  }),
]);

export function flattenVariants() {
  return PRINT_CATALOG.flatMap((work) => work.variants.map((variant) => ({ ...variant, work })));
}

export function findVariant(productId) {
  return flattenVariants().find((entry) => entry.id === productId) || null;
}
